version: "3"

services:
    db:
        image: postgres:15-alpine
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - "C:/Work/CollectionProject/collection-api/data:/var/lib/postgresql/data/"
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080

volumes:
    dbpg:
        driver: local
